### PR TITLE
BREAKING CHANGE: RxJS v6

### PR DESCRIPTION
**Pull request by rolaveric**
Update peer dependency and import paths to RxJS v6

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks for the PR @rolaveric! Will you update the commit message for the breaking change?

```
Commit message here

BREAKING CHANGE:

Description

BEFORE:

Usage before change

AFTER:

Usage after change
```

**Comment by rolaveric** [comment]
Commit message updated.

**Comment by brandonroberts** [comment]
Thanks!

**Comment by timbru31** [comment]
As a request for the next time: please stick to semver and release a breaking change via a major version bump, not a minor. Makes dependency management a lot easier.
Thanks ❤️

**Comment by timbru31** [comment]
Interesting, I've learnt something new today, too. Thanks for the hint :)

**Pull request merged**
