### PR TITLE
Added toEqualObservable jasmine matcher

### PR DESCRIPTION
**Pull request by PhillipZada**
See https://github.com/ngrx/platform/pull/204

### CODE REVIEW

**Comment by MikeRyanDev** [comment]
Sorry it took me a while to get to this one!

Is `toEqualObservable` equivalent in functionality to `toBeObservable` just with better error reporting? If so, I say replace the functionality of `toBeObservable` with `toEqualObservable` and I'll release this as 1.0.0

**Comment by PhillipZada** [comment]
Hey @MikeRyanDev,

Essentially yes, I just didn't know if there was any specific reason you where using toBe instead of toEqual, I'll put it together today and send it across, unless your happy with both options?

**Comment by PhillipZada** [comment]
Done

**Comment by brandonroberts** [comment]
Will you fix the merge conflicts and leave the matcher as `toBeObservable`?

**Comment by PhillipZada** [comment]
Reinit fork and created a new pull request

**Pull request closed without merging**
