### PR TITLE
refactor(unit-tests/coverage): update istanbul to 15 and add reporters

### PR DESCRIPTION
**Pull request by qdelettre**
- [x] Updated istanbul to 15 because 14 had issues related to coverage
- [x] Copy-pasted the matcher utils functions from rxjs, with changes related to jasmine instead of chai usage
- [x] Excluded the matcher utils from istanbul coverage, as it's only pasted here because not exposed by rxjs

I wil fix the coverage before asking for review ;)

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]
LGTM

**Comment by brandonroberts** [comment]
The changes are good, I'll land it when you're ready

**Comment by qdelettre** [comment]
Thanks @brandonroberts 

I will fix the coverage to 100% before merging, the else clause of this if https://github.com/synapse-wireless-labs/jasmine-marbles/blob/master/src/marble-unparser.ts#L30 is not yet tested. Do you have a clue ?

**Comment by brandonroberts** [comment]
I don't. Some of the code has been picked up from RxJS code and has been tested already, so I think the coverage is good as-is for now.

**Pull request merged**
