### PR TITLE
Support time progression syntax

### LINKED ISSUE #30: Time progression syntax issue, run mode issue, etc
I was playing around trying to get the time progression syntax working but began to run into quite a few hurdles.

First, the time progression syntax only works in the context of:

```javascript
getTestScheduler().run(() => {...})
```

If you look at the source code of `TestScheduler.parseMarbles` it needs to be in `runMode` for time progression syntax to be parsed.

My next thought is OK, I'll just wrap my code in `.run`. Turns out you can't use the `toBeObservable` matcher in inside of `.run` because https://github.com/synapse-wireless-labs/jasmine-marbles/blob/master/index.ts#L145 reparses the marbles and loses the context of `runMode` (note the last argument to `TestScheduler.parseMarbles` is `runMode`).

I think some careful consideration should be taken as some things should likely be redesigned to better work with `.run` for its advantages.

### PR DESCRIPTION
**Pull request by jonrimmer**
Fixes #30

### CODE REVIEW

**Comment by brandonroberts** [comment]
Will you add a test that confirms support for using `getTestScheduler().run(() => {})` also.

**Comment by jonrimmer** [comment]
@brandonroberts It doesn't support `.run()`. At least not reliably. The run method modifies the frame time from 10ms per frame to a new default of 1ms per frame. As such, observables created outside of `.run()` will not be compatible with those created inside it:

```ts
const provided = cold ('--a|');

getTestScheduler().run(() => {
  const expected = cold('--a|');
  expect(provided).toBeObservable(expected); // Fails
});
```

As I said in [ngrx#1740](https://github.com/ngrx/platform/issues/1740), RxJS really doesn't want you to create hold/cold observables for use in `run()` in any way except via the helpers it supplies, which are calibrated for the new settings used in `run()`, and not via external methods that be run inside or outside of it. I could modify the frame time of the singleton test scheduler to be 1ms, but that would be a breaking change for basically all code that uses this library. Issues like this are part of why I was suggesting discontinuing the use of this library altogether.

**Comment by brandonroberts** [comment]
I understand that. I was referring to adding a test using the standard syntax of `expectObaervable` inside the run method returned from `getTestScheduler()`. This is for those who want to use the standard syntax in some cases. I think there is still some utility in not having to set up the `TestScheduler.run()` method in each test.

**Comment by jonrimmer** [comment]
OK, no problem. Test added.

**Comment by brandonroberts** [comment]
Published as `0.5.0`

**Pull request merged**
